### ISSUE TITLE
Place catering order for lunch

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidy-dev-day#38]
Based on the catering menu, I would propose the signature sandwich buffet with curried chicken wrap, roast beef gorgonzola, and roasted butternut squash (if we can confirm that is indeed vegan)

so 18.5 * 1.1 * 90 = $1831.50 (the 10% is an overestimate of sales tax).

**Comment by jennybc** [comment]
We are feeding 96 people, total.

The various dietary requests:

* Gluten-free
* Halal (if possible)
* Lactose free
* Low carb
* No fish/seafood x4
* No peppers/tomatoes
* No red meat
* Vegetarian x11
* Nut and dairy allergy.
* Raw onions or scallions allergy

Hadley's proposal: 17 vegetarian to be safe (11 vegetarian + 4 no fish/seafood + 1 no red meat + 1 halal)

**Comment by jennybc** [comment]
I'm nailing down the order. It basically has to be a sandwich buffet, because of the distance to the Steam Plant Building (they are not able to roll over everything needed for, eg, the other buffet options). Re: the various dietary requests, they advise:

**Dietary Restriction Details:**

* We work in a shared kitchen facility where trace amounts may be present in the air or on surfaces.  Any guests with severe allergies are recommended to provide their own meals for safety
* We can indeed provide menu items that avoid gluten, nuts, dairy, seafood, peppers and/or onions as a direct ingredient, but trace amounts may be present
* We can craft meals that include vegetarian options (the butternut squash banh mi is the vegetarian option from the Signature Sandwich buffet and the side dish options are vegetarian)
* We do not offer Halal meals or meats. Many guests that request this are okay with just not having pork products, but each guest knows their dietary restrictions best
* If you go with the Signature Sandwich buffet, we can make some on bread that avoids gluten and pick the vegetarian bahn mi for vegetarians guests....Plus all the sides are vegetarian and avoid most dietary restrictions

**Comment by jennybc** [comment]
We are getting a sandwich buffet based on these 3 sandwiches:

* Curried chicken wrap. Contains red peppers and green onion.
* The grinder. A meat eaters option.
* Thai-style roasted butternut squash banh mi. This is the vegetarian option and 5 of these will also be prepared on bread that avoids gluten as an ingredient.
* Chips
* Broccoli slaw. Will be made with vegan mayo to avoid dairy.
* Rice Krispy Treats
* Assorted artisan cookies
* Water service (mix of plain large dispenser and seasonal spa water)

They don’t have a halal option, but 2 of the 3 sandwiches avoid pork.
No nuts are featured as an ingredient, but trace amounts may be present.
Dairy is present in the sandwiches.

We are not getting boxed lunches, but they have provided the boxed lunch menu for me to share because it offers the most detail on what's in the sandwiches.

[Boxed Lunch Order Form Aug 15.pdf](https://github.com/user-attachments/files/16446606/Boxed.Lunch.Order.Form.Aug.15.pdf)

Set up will happen between 11:30 and 12:00. We should be able to begin lunch at 12:00pm. They'll return at 2:30pm to clear buffet away.

@hadley In the welcome, please tell folks with specific dietary requests to consult this thread, if they want to know more about the lunch.
